### PR TITLE
Add template for getting env vars on Apiary deploys

### PR DESCRIPTION
**Pull request by brittanystoroz**
Generally, for each service deployed via apiary, we want to:

* First get all the stage consul/vault keys
* Merge those with any under the "dev" namespace, overriding the values of any duplicate keys
* Merge those with any provided in the service's `.env.default`, overriding the values of any duplicate keys

### CODE REVIEW

**Comment by brittanystoroz** [comment]
Confirmed with Patrick to change order of precedence to global stage - global dev - product stage - product dev - service stage - service dev - .env.default

**Comment by PurrBiscuit** [comment]
Looks good overall - curious why we don't use the `/dev` namespace in the export-consul.ctmpl like we do for the vault templates, even in the [dev consul template](https://github.com/articulate/docker-consul-template-bootstrap/blob/master/dev/export-consul.ctmpl).  I guess because we just store those consul type, non secret values in .env.default so it's not really necessary.

**Review by PurrBiscuit — APPROVED** [review]

**Comment by brittanystoroz** [comment]
@PurrBiscuit Thank you! Yes I had that question myself but figured I would start with this and then if we decided we wanted dev in consul as well, I could add it in later. I basically copy-pasta'd a mix of what dev/peer was currently doing for now 🤷 Thanks for looking!

**Pull request merged**
